### ISSUE TITLE
Roles in playbook-local collections in not working in Molecule 3.0.6 with ansible 2.10

### ISSUE THREAD

**Issue by geerlingguy** [ansible-community/molecule#2756]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ molecule --version
molecule 3.0.6
   ansible==2.10.0a3 python==3.7
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

Entire configuration is here: https://github.com/geerlingguy/ansible-content-testing

1. Git clone that repo
2. Install Ansible 2.10 distribution: `pip3 install --pre ansible>=2.10`
3. Run `molecule test` (uses Docker to bring up a `kind` instance)

# Desired Behavior

Roles that are in collections local to a playbook should be picked up and usable by Ansible.

See the `example.one` and `example.two` collections in the repository: https://github.com/geerlingguy/ansible-content-testing

# Actual Behaviour

```
    TASK [Include a 'test' role from 'example.one' collection.] ********************
ERROR! the role 'example.one.test' was not found in community.kubernetes:ansible.legacy:/Users/jgeerling/Development/GitHub/ansible-content-testing/molecule/default/../../roles:/Users/jgeerling/.cache/molecule/ansible-content-testing/default/roles:/Users/jgeerling/Development/GitHub:/Users/jgeerling/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/Users/jgeerling/Development/GitHub/ansible-content-testing/molecule/default/../..

The error appears to be in '/Users/jgeerling/Development/GitHub/ansible-content-testing/tasks/same-name-roles.yml': line 4, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  include_role:
    name: example.one.test
          ^ here
```

This started happening once 3.0.6 was released, and I believe the change in https://github.com/ansible-community/molecule/pull/2745 was what triggered the problem.

The molecule configuration is in the molecule subdirectory inside the ansible-content-testing repo.

**Comment by geerlingguy** [comment]
I can confirm with `--debug` that `ANSIBLE_COLLECTIONS_PATH=./` is set.

But when looking at the 'not found in' listing, it doesn't look like the playbook is even seeing the `example.one` and `example.two` collections, which are present inside the repository...

**Comment by geerlingguy** [comment]
Trying the following:

| Attempt | Pass/Fail |
| --- | --- | --- |
| `provisioner.env.ANSIBLE_COLLECTIONS_PATHS: ../` | Fail |
| | `provisioner.env.ANSIBLE_COLLECTIONS_PATHS: ../../` | TODO |

**Comment by geerlingguy** [comment]
Weird, with Ansible 2.9.10 installed I'm now getting:

```
--> Action: 'dependency'
ERROR! Unexpected Exception, this is probably a bug: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader' (/usr/local/lib/python3.7/site-packages/ansible/utils/collection_loader/__init__.py)
    the full traceback was:
    
    Traceback (most recent call last):
      File "/usr/local/bin/ansible-galaxy", line 92, in <module>
        mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
      File "/usr/local/lib/python3.7/site-packages/ansible/cli/__init__.py", line 22, in <module>
        from ansible.inventory.manager import InventoryManager
      File "/usr/local/lib/python3.7/site-packages/ansible/inventory/manager.py", line 38, in <module>
        from ansible.plugins.loader import inventory_loader
      File "/usr/local/lib/python3.7/site-packages/ansible/plugins/loader.py", line 26, in <module>
        from ansible.utils.collection_loader import AnsibleCollectionLoader, AnsibleFlatMapLoader, AnsibleCollectionRef
    ImportError: cannot import name 'AnsibleCollectionLoader' from 'ansible.utils.collection_loader' (/usr/local/lib/python3.7/site-packages/ansible/utils/collection_loader/__init__.py)
```

**Comment by geerlingguy** [comment]
So it looks like for now, if I want to build a molecule config for a playbook that works in both 2.9 and 2.10, I have to define both the old and new env vars:

```yaml
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATHS: ../../
    ANSIBLE_COLLECTIONS_PATH: ../../
```

**Comment by stiller-leser** [comment]
For me the fix from https://github.com/ansible-community/molecule/issues/2756#issuecomment-661186700 works wonders. The environment variable changes do not change anything for me.
